### ISSUE TITLE
Header hight, Header 2, icon

### ISSUE THREAD

**Issue by Tom-ahawk** [nervetattoo/banner-card#7]
Great card! Make Banner Card greater, with some more customization, please.

1.	Main header area high customization.
2.	Header 2, - a header text over the sensor row. In my example “Sun today”, “Sun tomrorw”
3.    Display sensor icon and/or sensor name as the entitie name, in the card
4. entities[].attribute, when attribute is "entity_picture:", picture is not displayed (like my moon sensor).
5. Customize row_size for each row. Like I would like to have my moon sensor in between today row, and tomorow row.

![image](https://user-images.githubusercontent.com/35527507/58271656-cfff0180-7d8c-11e9-807b-974daaef3178.png)

Just my 2C.

**Comment by aptonline** [comment]
To add to this the ability to auto change the text colour contrast based on the backgroup colour (light/dark)

Also the text size.

**Comment by nervetattoo** [comment]
@aptonline 
Text size can be changed with CSS variables I've just not documented their names.
Automatic text color contrast were something I thought about but decided to defer until someone asked :) Getting a nice list of stuff for a new release now.

@Tom-ahawk 
1. Will probably make that tweakable via theme/card-modder
2. Not doing
3. Not doing
4. That makes sense to support
5. They aren't clear rows, its a list of items that wraps and thats how I want it, so that won't happen. But using row_size + size you can achieve anything if you just find a common denominator :)

**Comment by nervetattoo** [comment]
Some stuff relating to this released in 0.5.0, closing issue
